### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'Input.decl')

### ISSUE THREAD

**Issue by verybigman** [enb-bem/enb-bem-specs#16]
Как с этим бороться? Понятно только что проблема с депсами, что мол они не объект, только вот они все массив так-то. @andrewblond  ты не в курсе?

**Comment by andrewblond** [comment]
Привет! Можешь добавить немного подробностей?

**Comment by verybigman** [comment]
Да, канеш, сорри:) я создаю модификатор блоку `input` в `input_type_link.browser.js`.

``` js
modules.define('input', function(provide, Input) {
    provide(Input.decl({ block : this.name, modName : 'type', modVal : 'link' }, {}));
});
```

в депсах у модификатора пишу
``` js
[{
    tech : 'spec.js',
    mustDeps : [
        { tech : 'bemhtml', block : 'input', mods : { type: 'link'} }
    ]
}]
```

Пишу тест. Пустой даже. И получаю эту ошибку. Долгое изыскание принесло понимание, что дело не в втоих спеках, а в модульной системе походу. И следующая запись решила проблему, но так как-то не тру.

``` js
provide(BEMDOM.decl({ block : this.name, modName : 'type', modVal : 'link' }, {}));
```

**Comment by tadatuta** [comment]
@verybigman попробуй не задавать `block : this.name`. В bem-components как раз в `input` [есть](https://github.com/bem/bem-components/blob/v2/desktop.blocks/input/_autofocus/input_autofocus.js) [модификаторы](https://github.com/bem/bem-components/blob/v2/desktop.blocks/input/_has-clear/input_has-clear.js) и тесты собираются нормально.

**Comment by verybigman** [comment]
По-моему, это не решает проблему, получаю ошибку на decl
Пт, 30 янв. 2015 г. в 23:08, Vladimir Grinenko <notifications@github.com>:

**Comment by tadatuta** [comment]
@verybigman тогда ждем тест-кейс, на котором можно было бы поэкспериментировать

**Comment by verybigman** [comment]
Сделал копию bem-components репозитория, удалили все блоки, добавил свои и подключил bem-compnents вот тут https://github.com/verybigman/test-case/tree/master/common.blocks/input/_type
Проблема воспроизводиться:)

**Comment by tadatuta** [comment]
@verybigman пока понятно только, что проблема в порядке подключения зависимостей — код модификатора идет раньше, чем код самого блока, поэтому `Input.decl()` и падает.
При этом в собранном deps.js порядок верный, так что с большой долей вероятности проблема таки в `enb-bem-specs`.

**Comment by verybigman** [comment]
Это очень грустно. Объявление через BEMDOM помогает, но блок тогда не инитится в тестах

**Comment by tadatuta** [comment]
Не грусти, у нас есть волшебный @andrewblond, он обязательно все починит ;)

**Comment by verybigman** [comment]
Будем ждать:) Спасибо за помощь!

**Comment by verybigman** [comment]
Мужчины! Тут выяснилось внезапно, что все дело в суффиксах технологий. По каким-то причинам *.js собирается после *.browser.js. Через *.js все описано в компонентах и нет там *.browser.js. Хотя как по мне, то должно собираться *.vanilla.js -> *.browser.js, *.vanilla.js -> *.node.js

**Comment by andrewblond** [comment]
Cуффикс `js` по смыслу является алиасом для `browser.js`, поэтому не должно быть никакой разницы в том, что из этого будет раньше, а что позже.

При этом `vanilla.js` действительно собирается раньше чем `browser.js` и `js`.

Может где-то `js` использовался как алиас к `vanilla.js` и это нужно исправить, переименовав файлы в `vanilla.js`?

**Comment by verybigman** [comment]
Проверим, напишу че как. Еще в тестах как-то криво собирается bemhtml:) ретурн контекста раньше условий блока в бандле. Пока грешу на мердж. Разбиремся.

**Comment by dragn** [comment]
@verybigman @andrewblond по поводу "кривой сборки bemhtml" завел отдельную заявку #18

**Comment by tadatuta** [comment]
отдельную заявку закрыл ;)

**Comment by verybigman** [comment]
@tadatuta спасибо!

**Comment by blond** [comment]
Вроде всё решилось? Закрываю задачу, если, что не стесняйтесь переоткрыть ;)
