### ISSUE TITLE
Specs for node.js tech

### ISSUE THREAD

**Issue by verybigman** [enb-bem/enb-bem-specs#17]
Хочу сделать технологию для тестов блоков в node.js технологии. Вроде как надо только убрать проброс тестов в фантом и все. Пни в нужную сторону, пожалуйста:)

**Comment by andrewblond** [comment]
Для тестов под node.js, нужно будет выпилить почти всё из этого пакета =)

Всё, что нужно будет сделать:

1. Собрать `spec.node.js` файлы в сеты.
2. Запустить `mocha` для каждого бандла в сетах.

Сейчас запуском тестов + подсчётом `coverage` занимается https://github.com/enb-bem/enb-bem-specs/blob/master/lib/runner.js. Если нужен coverage, то раннеру нужно подавать уже проинструментированный код.

Сеты сейчас собираются этим кодом: https://github.com/enb-bem/enb-bem-specs/blob/master/lib/plugin.js#L34-L94.

Не думаю, что объяснил =) Проще будет отвечать на более наводящие вопросы.

**Comment by verybigman** [comment]
Ага:) радует, что писать сильно меньше:)

**Comment by verybigman** [comment]
Ок, я тогда когда дойду, напишу более предметно. Спасибо!

**Comment by dragn** [comment]
Набросал плагин: [enb-bem-node-specs](https://github.com/dragn/enb-bem-node-specs)

**Comment by verybigman** [comment]
@dragn спасибо!
