### ISSUE TITLE
Specs for block are running several times

### ISSUE THREAD

**Issue by narqo** [enb-bem/enb-bem-specs#19]
If we have separate specs in block's element (or for element with modifier), specs for block will be run several times for every nested BEM entity. 

For example: [this "i-bem decl" suite-case][1] have been started as part of `desktop.specs/i-bem__dom/i-bem__dom.html` specs (and several times later), while it already had been run in the `desktop.specs/i-bem/i-bem.html`.

[1]: https://travis-ci.org/bem/bem-core/builds/50344211#L2254

**Comment by andrewblond** [comment]
Fixed in `v0.5.5`.

**Comment by veged** [comment]
can you publish it?

**Comment by andrewblond** [comment]
@veged, done!
