### ISSUE TITLE
Failed tests doesn't affect "build" result, critical

### ISSUE THREAD

**Issue by zxqfox** [enb-bem/enb-bem-specs#21]
Ref https://github.com/bem/bem-core/pull/842#issuecomment-77510001
Ref https://travis-ci.org/bem/bem-core/builds/48876496#L2388

/cc @tadatuta @narqo

**Comment by andrewblond** [comment]
This was fixed in `enb-bem-specs@0.5.4` and `enb-magic-platform@0.4.4.`.

**Comment by zxqfox** [comment]
:+1: Thanks
